const crypto=require('crypto');
const {neon}=require('@neondatabase/serverless');
const ui=require('../lib/ui');
const {esc,attr,layout}=ui;
function db(){if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL não configurada');return neon(process.env.DATABASE_URL)}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x[0]))}
function sig(v){return crypto.createHmac('sha256',process.env.SESSION_SECRET||'').update(v).digest('base64url')}
function isAdmin(req){try{const t=cookies(req).ep_session;if(!t)return false;const [p,s]=t.split('.');if(!p||!s)return false;const a=Buffer.from(s),b=Buffer.from(sig(p));if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return false;const d=JSON.parse(Buffer.from(p,'base64url').toString());return d.exp>Date.now()&&d.email===process.env.ADMIN_EMAIL}catch{return false}}
function body(req){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>1_500_000)req.destroy()});req.on('end',()=>{try{resolve(JSON.parse(d||'{}'))}catch{resolve({})}});req.on('error',reject)})}
function safeItems(raw){return (Array.isArray(raw)?raw:[]).slice(0,10).map((x,i)=>({url:String(x?.url||'').trim().slice(0,1200),caption:String(x?.caption||'').trim().slice(0,500),alt_text:String(x?.alt_text||'').trim().slice(0,500),credit:String(x?.credit||'').trim().slice(0,250),sort_order:i})).filter(x=>x.url&&(/^https?:\/\//i.test(x.url)||x.url.startsWith('/')))}
async function list(sql,articleId){return sql`SELECT id,url,caption,alt_text,credit,sort_order FROM article_gallery WHERE article_id=${articleId} ORDER BY sort_order ASC,created_at ASC`}
module.exports=async(req,res)=>{try{const sql=db();if(req.method==='GET'&&String(req.query?.view||'')==='json'){const slug=String(req.query?.slug||'');const a=(await sql`SELECT id FROM articles WHERE slug=${slug} AND status='published' LIMIT 1`)[0];res.setHeader('Cache-Control','public, max-age=60');return res.status(200).json(a?await list(sql,a.id):[])}if(req.method==='GET'){if(!isAdmin(req))return res.redirect(303,'/admin/login');const id=String(req.query?.id||'');const a=(await sql`SELECT id,title,cover_url,cover_alt FROM articles WHERE id=${id} LIMIT 1`)[0];if(!a)return res.status(404).send(layout('Galeria não encontrada','<main class="empty"><h1>Matéria não encontrada</h1><a class="btn" href="/admin">Voltar</a></main>',true));const items=await list(sql,id);const data=attr(JSON.stringify(items));const content=`<header class="top"><div class="shell nav"><a href="/admin"><img class="logo" src="/logo.svg" alt="Em Pauta"></a><div class="actions" style="margin-left:auto"><a class="ghost" href="/admin?edit=${attr(id)}">Editar matéria</a><a class="ghost" target="_blank" href="/">Ver portal</a></div></div></header><main class="shell adminMain"><section class="panel"><div class="eye">GALERIA</div><h1>${esc(a.title)}</h1><p class="notice">Adicione até 10 fotos. Preencha legenda, texto alternativo e crédito antes de salvar.</p><div id="galleryManager" data-article-id="${attr(id)}" data-items="${data}"></div></section></main>`;return res.status(200).send(layout('Galeria da matéria',content,true))}if(req.method==='POST'){if(!isAdmin(req))return res.status(401).json({error:'Não autorizado.'});const b=await body(req),id=String(b.articleId||''),action=String(b.action||'save');const a=(await sql`SELECT id FROM articles WHERE id=${id} LIMIT 1`)[0];if(!a)return res.status(404).json({error:'Matéria não encontrada.'});if(action==='cover'){const url=String(b.url||'').slice(0,1200),alt=String(b.alt_text||'').slice(0,500);await sql`UPDATE articles SET cover_url=${url},cover_alt=${alt},updated_at=now() WHERE id=${id}`;return res.status(200).json({ok:true})}const items=safeItems(b.items);await sql`DELETE FROM article_gallery WHERE article_id=${id}`;for(const item of items){await sql`INSERT INTO article_gallery(id,article_id,url,caption,alt_text,credit,sort_order) VALUES(${crypto.randomUUID()},${id},${item.url},${item.caption},${item.alt_text},${item.credit},${item.sort_order})`}return res.status(200).json({ok:true,count:items.length})}return res.status(405).end()}catch(e){console.error(e);return res.status(500).json({error:'Não foi possível processar a galeria.'})}};
