const crypto=require('crypto');
const {neon}=require('@neondatabase/serverless');

const MAX=2.5*1024*1024;
const ALLOWED=new Set(['image/jpeg','image/png','image/webp']);
function sql(){if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL não configurada');return neon(process.env.DATABASE_URL)}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x[0]))}
function sig(v){return crypto.createHmac('sha256',process.env.SESSION_SECRET||'').update(v).digest('base64url')}
function isAdmin(req){try{const t=cookies(req).ep_session;if(!t)return false;const [p,s]=t.split('.');if(!p||!s)return false;const a=Buffer.from(s),b=Buffer.from(sig(p));if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return false;const d=JSON.parse(Buffer.from(p,'base64url').toString());return d.exp>Date.now()&&d.email===process.env.ADMIN_EMAIL}catch{return false}}
function parse(data=''){const m=/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/.exec(String(data));if(!m)return null;const bytes=Buffer.from(m[2],'base64');if(!ALLOWED.has(m[1])||!bytes.length||bytes.length>MAX)return null;return {mime:m[1],bytes}}
function ipHash(req){const ip=String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim();return crypto.createHmac('sha256',process.env.SESSION_SECRET||'em-pauta').update(ip).digest('hex')}
module.exports=async(req,res)=>{try{const db=sql();if(req.method==='GET'){const id=String(req.query?.id||'');if(!id)return res.status(400).end();const rows=await db`SELECT mime_type,file_name,bytes,size_bytes FROM media WHERE id=${id} LIMIT 1`;if(!rows.length)return res.status(404).end();const r=rows[0],buf=Buffer.isBuffer(r.bytes)?r.bytes:Buffer.from(r.bytes);res.setHeader('Content-Type',r.mime_type);res.setHeader('Content-Length',String(r.size_bytes));res.setHeader('Cache-Control','public, max-age=31536000, immutable');return res.status(200).send(buf)}if(req.method!=='POST')return res.status(405).end();const body=req.body||{},purpose=String(body.purpose||'pauta');if(purpose==='admin'&&!isAdmin(req))return res.status(401).json({error:'Não autorizado.'});if(purpose!=='admin'){const h=ipHash(req);const n=await db`SELECT count(*)::int n FROM upload_events WHERE ip_hash=${h} AND created_at>now()-interval '1 hour'`;if((n[0]?.n||0)>=5)return res.status(429).json({error:'Limite de anexos atingido. Tente novamente mais tarde.'});await db`INSERT INTO upload_events(id,ip_hash) VALUES(${crypto.randomUUID()},${h})`}const parsed=parse(body.dataUrl);if(!parsed)return res.status(400).json({error:'Envie JPG, PNG ou WebP com até 2,5 MB.'});const id=crypto.randomUUID(),name=String(body.fileName||'imagem').slice(0,160);await db`INSERT INTO media(id,mime_type,file_name,bytes,size_bytes,uploaded_by) VALUES(${id},${parsed.mime},${name},${parsed.bytes},${parsed.bytes.length},${purpose==='admin'?'admin':'reader'})`;return res.status(200).json({ok:true,url:`/api/upload?id=${encodeURIComponent(id)}`})}catch(e){console.error(e);return res.status(500).json({error:'Não foi possível processar a imagem.'})}};
